version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: youvideo
      POSTGRES_PASSWORD: youvideo_pass
      POSTGRES_DB: you_video
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./server/.env.example
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server:/app

  worker:
    build: ./server
    command: node /app/worker/worker.js
    restart: unless-stopped
    env_file:
      - ./server/.env.example
    depends_on:
      - db
    volumes:
      - ./server/uploads:/app/uploads
      - ./server:/app

volumes:
  db-data:
